"""
Django settings for D_Bots project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
""

from pathlib import Path
import os
import environ

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8s786t6sbmkbzl+lqs@2v1-5vrd$e25(ja-tim+v2e11y%95bh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['kkmaina.onrender.com', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    "daphne",  # ASGI server
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'core.apps.CoreConfig',
    'botbuilder.apps.BotbuilderConfig',
    'ws',  # Your WebSocket app
    'tutorials.apps.TutorialsConfig',
    'freebots.apps.FreebotsConfig',
    'users.apps.UsersConfig',
    "whitenoise.runserver_nostatic",  # ADD THIS before 'django.contrib.staticfiles'
    "copy_trading",
    "tracking",
    # 'corsheaders',
]

# Add rest framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
}

MIDDLEWARE = [
    #'corsheaders.middleware.CorsMiddleware',  # Add this before other middlewares
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # ADD THIS
]

# Allow all origins for testing (use specific domains in production)
#CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'D_Bots.urls'
# trading_platform/settings.py

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'D_Bots', 'templates')],  # ✅ Scoped properly
        'APP_DIRS': True,  # Looks for templates/ inside each app automatically
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'D_Bots.asgi.application'

import os
from dotenv import load_dotenv

load_dotenv()

# 🔐 Load sensitive keys
FERNET_KEY = os.getenv("FERNET_KEY")
REDIS_URL = os.getenv("REDIS_URL")

if not REDIS_URL:
    raise ValueError("❌ REDIS_URL not set in .env")

# 🧠 Channel layer configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# Set Daphne WebSocket timeout
WS_TIMEOUT = 3600  # 1 hour timeout (increase if needed)


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_USER_MODEL = 'users.CustomUser'
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Add static files directories
STATICFILES_DIRS = [
     BASE_DIR / "static",
]



# Define static files directory (if you have a custom static directory)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Directory to collect static files for deployment
STATIC_ROOT = BASE_DIR / "staticfiles"

# Ensure you have this for deployment
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# WhiteNoise settings for caching and compression
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"